apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o charts -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o charts -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/09me-discord-bot-internal: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: IsDiscord
              value: "true"
          image: wjervis7/09me-website:latest
          name: web
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /configs
              name: configs
      restartPolicy: Always
      volumes:
        - name: configs
          persistentVolumeClaim:
            claimName: configs
status: {}
