version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD
    ports:
      - 1433:1433
    volumes:
      - sql:/var/opt/mssql/data
    networks:
      - internal
  bot:
    image: wjervis7/09me-discord:latest
    environment:
      - IsDiscord=true
      - ConnectionStrings__DefaultConnection=Server=database;Database=09ME;User=SA;Password=$(MSSQL_SA_PASSWORD)
      - Discord__ClientId=$(DiscordClientId)
      - Discord__ClientSecret=$(DiscordClientSecret)
      - Discord__Token=$(DiscordToken)
      - Discord__GuildId=$(DiscordGuildId)
    volumes:
      - configs:/configs
    networks:
      - internal
  web:
    image: wjervis7/09me-website:latest
    environment:
      - IsDiscord=true
    ports:
      - 80:80
    volumes:
      - configs:/configs
    networks:
      - internal

networks:
  internal:

volumes:
  sql:
  configs:
