name: publish docker images images

on:
  push:
    branches:
      - 'dev'
      - 'master'
    tags:
      - 'v*'

jobs:

  build:
  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set output
        id: vars
        run: echo ::set-output name=branch::${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      
      - name: Extract metadata (tags, labels) for Docker - bot
        id: meta-bot
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/09me-discord
          flavor: |
            latest=${{ steps.vars.outputs.branch == 'master' }}
          tags: |
            type=raw,value=beta,enable=${{ steps.vars.outputs.branch == 'dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Extract metadata (tags, labels) for Docker - web
        id: meta-web
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/09me-website
          flavor: |
            latest=${{ steps.vars.outputs.branch == 'master' }}
          tags: |
            type=raw,value=beta,enable=${{ steps.vars.outputs.branch == 'dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Build and push Docker image - bot
        uses: docker/build-push-action@v2.8.0
        with:
          context: 09.Mass.Extinction.Discord.Bot
          push: ${{ steps.vars.outputs.branch == 'dev' }} 
          tags: ${{ steps.meta-bot.outputs.tags }}
          labels: ${{ steps.meta-bot.outputs.labels }}  
          
      - name: Build and push Docker image - web
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          file: 09.Mass.Extinction.Web/Dockerfile
          push: ${{ steps.vars.outputs.branch == 'dev' }} 
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}  
