name: publish docker images

on:
  push:
    branches:
      - 'dev'
      - 'master'
    tags:
      - 'v*'

jobs:

  build:
  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set output
        id: vars
        run: echo ::set-output name=branch::${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        
      - name: Check output
        run: echo ${{ steps.vars.outputs.branch }}
      
      - name: Extract metadata (tags, labels) for Docker - bot
        id: meta-bot
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/09me-discord
            ghcr.io/${{ github.repository_owner }}/09me-discord
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ steps.vars.outputs.branch == 'master' }}
            type=raw,value=beta,enable=${{ steps.vars.outputs.branch == 'dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Extract metadata (tags, labels) for Docker - web
        id: meta-web
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/09me-website
            ghcr.io/${{ github.repository_owner }}/09me-website
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ steps.vars.outputs.branch == 'master' }}
            type=raw,value=beta,enable=${{ steps.vars.outputs.branch == 'dev' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}  
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Build and push Docker image - bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 09.Mass.Extinction.Discord.Service/Dockerfile
          push: true
          tags: ${{ steps.meta-bot.outputs.tags }}
          labels: ${{ steps.meta-bot.outputs.labels }}  
          platforms: linux/amd64
          
      - name: Build and push Docker image - web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 09.Mass.Extinction.Web/Dockerfile
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}  
          platforms: linux/amd64          
