name: publish wjervis7/09me-discord:beta

on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'

jobs:

  build:
  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker - bot
        id: meta-bot
        uses: docker/metadata-action@v3.6.2
        with:
          images: wjervis7/09me-discord
          tags: |
            type=ref,event=tag
            type=raw,value=beta,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Extract metadata (tags, labels) for Docker - web
        id: meta-web
        uses: docker/metadata-action@v3.6.2
        with:
          images: wjervis7/09me-website
          tags: |
            type=ref,event=tag
            type=raw,value=beta,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Set output
        id: vars
        run: echo ::set-output name=branch::${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
      - name: Check output
        run: echo ${{ steps.vars.outputs.branch }}
      
      - name: Build and push Docker image - bot
        uses: docker/build-push-action@v2.8.0
        with:
          context: 09.Mass.Extinction.Discord.Bot
          push: ${{ steps.vars.outputs.branch == 'dev' }} 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}  
          
      - name: Build and push Docker image - web
        uses: docker/build-push-action@v2.8.0
        with:
          context: 09.Mass.Extinction.Discord.Web
          push: ${{ steps.vars.outputs.branch == 'dev' }} 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}  
